# Generated by Django 6.0.3 on 2026-04-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/'),
        ),
    ]
